### ISSUE TITLE
Direct Ysoserial Support

### ISSUE THREAD

**Issue by h0ng10** [mogwailabs/rogue-jndi-ng#3]
Include a Controller that allows to directly deserialize a ysoserial payload.

Instead of creating a large number of Controllers (one for each Gadget Chain in ysoserial), it makes more sense to create one endpoint and provide the actual serialized payload as file. The LDAP service loads the serialized object from the file and passes it in the response.

This is more flexible and allows the usage of custom gadget chains.

**Comment by theGEBIRGE** [comment]
Implemented with dfde773c62df0f3af28f6eac7f8e3c868d4970e4.
