### ISSUE TITLE
Add H2 endpoint

### ISSUE THREAD

**Issue by h0ng10** [mogwailabs/rogue-jndi-ng#5]
While writing the [Look Mama, no TemplatesImpl](https://mogwailabs.de/en/blog/2023/04/look-mama-no-templatesimpl/) blogpost, I created a [controller for H2](https://github.com/artsploit/rogue-jndi/pull/1/files), which was never merged into the rouge-jndi project.

**Comment by theGEBIRGE** [comment]
Implemented with e89a2a9d18620614315eac376e96dfa1c8171b84.
