### ISSUE TITLE
Add Test Containers

### ISSUE THREAD

**Issue by h0ng10** [mogwailabs/rogue-jndi-ng#6]
It would be great to have some test containers that can be used to test that everything works as expected, for example Tomcat in different versions, using different Java versions.

The idea would be to create a minimal web servlet that creates an outgoing JNDI request to an URL that is passed as parameter. The servlet can then be deployed in different containers

**Comment by theGEBIRGE** [comment]
Implemented with 279d5bdd5e6e7e93a4e5e8d81ba9c9a8b9807124.
